grpc:
  host: "localhost"
  port: 7003

collector:
  host: "localhost"
  port: 7002

redis:
  host: "localhost"
  port: 6379

discovery-grpc-client:
  host: "localhost"
  port: 7001

discovery-grpc-server:
  host: "localhost"
  port: 7001